# **Progetto di analisi sugli aeroporti USA nei mesi di luglio-agosto**

## **Pulizia e formattazione dei dati**

#### 1. Installing needed libraries

In [ ]:
!pip install pandas
!pip install numpy
!pip install airportsdata

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Collecting airportsdata
  Downloading airportsdata-20241001-py3-none-any.whl.metadata (8.9 kB)
Downloading airportsdata-20241001-py3-none-any.whl (912 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 912.7/912.7 kB 10.4 MB/s eta 0:00:00
Installing collected packages: airportsdata
Successfully installed airportsdata-20241001

#### 2. Importing needed libraries

In [ ]:
# Data manipulation
import numpy as np
import pandas as pd

# Airports data
from airportsdata import load

# Date manipulation
from datetime import datetime
from datetime import date

# Time zone manipulation
from zoneinfo import ZoneInfo

# File manipulation
import glob

#### 3. Set up Google Drive for Colab (if need to use Colab)

In [ ]:
# Importing file from Google drive for Colab to use
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

#### 4. Set up pandas

In [ ]:
# View all columns
pd.set_option('display.max_columns', None)

#### 5. Importing airports data

In [ ]:
# Load airports data using airports IATA code
airports = load('IATA')

In [ ]:
airports.get("OCA")

{'icao': '07FA',
 'iata': 'OCA',
 'name': 'Ocean Reef Club Airport',
 'city': 'Key Largo',
 'subd': 'Florida',
 'country': 'US',
 'elevation': 6.0,
 'lat': 25.32432,
 'lon': -80.27573,
 'tz': 'America/New_York',
 'lid': '07FA'}

#### 6. Importing csv files

In [ ]:
# Without using Colab

# # Read all csv file from csv folder
# csv_files = glob.glob("csv/*.csv")

# # Concat all data from all csv files into 1 single pandas dataframe
# df_list = []

# for file_path in csv_files:
#     df = pd.read_csv(file_path)
#     df_list.append(df)

# df = pd.concat(df_list, ignore_index=True)

In [ ]:
# Google colab

# Same setup of above
csv_files = glob.glob("/content/drive/MyDrive/csv/*.csv")

df_list = []

for file_path in csv_files:
    df = pd.read_csv(file_path)
    df_list.append(df)

df = pd.concat(df_list, ignore_index=True)

#### 7. View imported dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1253638 entries, 0 to 1253637
Data columns (total 45 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   YEAR                   1253638 non-null  int64
 1   MONTH                  1253638 non-null  int64
 2   DAY_OF_MONTH           1253638 non-null  int64
 3   OP_UNIQUE_CARRIER      1253638 non-null  object
 4   OP_CARRIER_AIRLINE_ID  1253638 non-null  int64
 5   OP_CARRIER             1253638 non-null  object
 6   TAIL_NUM               1247829 non-null  object
 7   OP_CARRIER_FL_NUM      1253637 non-null  float64
 8   ORIGIN_AIRPORT_ID      1253638 non-null  int64
 9   ORIGIN_AIRPORT_SEQ_ID  1253638 non-null  int64
 10  ORIGIN_CITY_MARKET_ID  1253638 non-null  int64
 11  ORIGIN                 1253638 non-null  object
 12  ORIGIN_CITY_NAME       1253638 non-null  object
 13  ORIGIN_STATE_ABR       1253638 non-null  object
 14  ORIGIN_STATE_FIPS      1253638 non-null  int64
 15  ORIGIN_STATE_NM        1253638 non-null  object
 16  DEST_AIRPORT_ID        1253638 non-null  int64
 17  DEST_AIRPORT_SEQ_ID    1253638 non-null  int64
 18  DEST_CITY_MARKET_ID    1253638 non-null  int64
 19  DEST                   1253638 non-null  object
 20  DEST_CITY_NAME         1253638 non-null  object
 21  DEST_STATE_ABR         1253638 non-null  object
 22  DEST_STATE_FIPS        1253638 non-null  int64
 23  DEST_STATE_NM          1253638 non-null  object
 24  CRS_DEP_TIME           1253638 non-null  int64
 25  DEP_TIME               1223755 non-null  float64
 26  DEP_DELAY              1223698 non-null  float64
 27  DEP_DELAY_NEW          1223698 non-null  float64
 28  CRS_ARR_TIME           1253638 non-null  int64
 29  ARR_TIME               1222283 non-null  float64
 30  ARR_DELAY              1218241 non-null  float64
 31  ARR_DELAY_NEW          1218241 non-null  float64
 32  CANCELLED              1253638 non-null  float64
 33  CANCELLATION_CODE      31086 non-null    object
 34  DIVERTED               1253638 non-null  float64
 35  CRS_ELAPSED_TIME       1253638 non-null  float64
 36  ACTUAL_ELAPSED_TIME    1218241 non-null  float64
 37  AIR_TIME               1218241 non-null  float64
 38  FLIGHTS                1253638 non-null  float64
 39  DISTANCE               1253638 non-null  float64
 40  CARRIER_DELAY          323675 non-null   float64
 41  WEATHER_DELAY          323675 non-null   float64
 42  NAS_DELAY              323675 non-null   float64
 43  SECURITY_DELAY         323675 non-null   float64
 44  LATE_AIRCRAFT_DELAY    323675 non-null   float64
dtypes: float64(19), int64(14), object(12)
memory usage: 430.4+ MB

In [ ]:
df

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1812,1808.0,-4.0,0.0,2015,1950.0,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,825,819.0,-6.0,0.0,923,916.0,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,1200,1157.0,-3.0,0.0,1457,1445.0,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,1621,1624.0,3.0,3.0,1732,1733.0,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,2110,2110.0,0.0,0.0,2242,2221.0,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1450,1446.0,-4.0,0.0,1608,1642.0,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,1250,1240.0,-10.0,0.0,1409,1343.0,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1000,953.0,-7.0,0.0,1125,1122.0,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,944,940.0,-4.0,0.0,1158,1134.0,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,1250,1243.0,-7.0,0.0,1305,1254.0,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe()

,YEAR,MONTH,DAY_OF_MONTH,OP_CARRIER_AIRLINE_ID,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_STATE_FIPS,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
count,1253638.0,1.253638e+06,1.253638e+06,1.253638e+06,1.253637e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.223755e+06,1.223698e+06,1.223698e+06,1.253638e+06,1.222283e+06,1.218241e+06,1.218241e+06,1.253638e+06,1.253638e+06,1.253638e+06,1.218241e+06,1.218241e+06,1253638.0,1.253638e+06,323675.000000,323675.000000,323675.000000,323675.000000,323675.000000
mean,2024.0,7.493783e+00,1.596115e+01,1.995357e+04,2.520828e+03,1.264215e+04,1.264219e+06,3.172992e+04,2.727662e+01,1.264217e+04,1.264221e+06,3.172995e+04,2.727605e+01,1.331651e+03,1.333572e+03,1.885770e+01,2.172579e+01,1.483687e+03,1.439638e+03,1.436963e+01,2.175943e+01,2.479663e-02,3.438792e-03,1.459670e+02,1.414707e+02,1.145884e+02,1.0,8.402076e+02,27.635366,4.009534,13.945257,0.109514,32.345544
std,0.0,4.999615e-01,8.907023e+00,3.698977e+02,1.648983e+03,1.536321e+03,1.536319e+05,1.327622e+03,1.671722e+01,1.536319e+03,1.536317e+05,1.327600e+03,1.671656e+01,4.983029e+02,5.216544e+02,6.538868e+01,6.432480e+01,5.273306e+02,5.663856e+02,6.710714e+01,6.405211e+01,1.555049e-01,5.854032e-02,7.220088e+01,7.257191e+01,7.022461e+01,0.0,6.053377e+02,79.623662,29.534719,34.412011,2.400925,66.518617
min,2024.0,7.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,1.000000e+00,-5.000000e+01,0.000000e+00,1.000000e+00,1.000000e+00,-8.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01,1.500000e+01,5.000000e+00,1.0,1.100000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024.0,7.000000e+00,8.000000e+00,1.979000e+04,1.154000e+03,1.129200e+04,1.129202e+06,3.061500e+04,1.200000e+01,1.129200e+04,1.129202e+06,3.061500e+04,1.200000e+01,9.050000e+02,9.050000e+02,-5.000000e+00,0.000000e+00,1.055000e+03,1.027000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.300000e+01,8.800000e+01,6.300000e+01,1.0,3.990000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2024.0,7.000000e+00,1.600000e+01,1.993000e+04,2.265000e+03,1.288900e+04,1.288904e+06,3.145300e+04,2.600000e+01,1.288900e+04,1.288904e+06,3.145300e+04,2.600000e+01,1.325000e+03,1.325000e+03,-1.000000e+00,0.000000e+00,1.513000e+03,1.450000e+03,-4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.290000e+02,1.250000e+02,9.700000e+01,1.0,6.790000e+02,4.000000,0.000000,0.000000,0.000000,8.000000
75%,2024.0,8.000000e+00,2.400000e+01,2.036300e+04,3.765000e+03,1.405700e+04,1.405702e+06,3.247400e+04,4.200000e+01,1.405700e+04,1.405702e+06,3.247400e+04,4.200000e+01,1.743000e+03,1.754000e+03,1.600000e+01,1.600000e+01,1.925000e+03,1.916000e+03,1.700000e+01,1.700000e+01,0.000000e+00,0.000000e+00,1.750000e+02,1.720000e+02,1.440000e+02,1.0,1.069000e+03,23.000000,0.000000,17.000000,0.000000,39.000000
max,2024.0,8.000000e+00,3.100000e+01,2.045200e+04,8.819000e+03,1.686900e+04,1.686902e+06,3.599100e+04,7.800000e+01,1.686900e+04,1.686902e+06,3.599100e+04,7.800000e+01,2.359000e+03,2.400000e+03,3.777000e+03,3.777000e+03,2.359000e+03,2.400000e+03,3.803000e+03,3.803000e+03,1.000000e+00,1.000000e+00,1.326000e+03,7.150000e+02,6.620000e+02,1.0,5.095000e+03,3689.000000,1439.000000,1386.000000,512.000000,2305.000000

In [ ]:
df.head()

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1812,1808.0,-4.0,0.0,2015,1950.0,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,825,819.0,-6.0,0.0,923,916.0,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,1200,1157.0,-3.0,0.0,1457,1445.0,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,1621,1624.0,3.0,3.0,1732,1733.0,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,2110,2110.0,0.0,0.0,2242,2221.0,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail()

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1450,1446.0,-4.0,0.0,1608,1642.0,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,1250,1240.0,-10.0,0.0,1409,1343.0,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1000,953.0,-7.0,0.0,1125,1122.0,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,944,940.0,-4.0,0.0,1158,1134.0,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,1250,1243.0,-7.0,0.0,1305,1254.0,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'OP_UNIQUE_CARRIER',
       'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER', 'TAIL_NUM', 'OP_CARRIER_FL_NUM',
       'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID',
       'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_FIPS',
       'ORIGIN_STATE_NM', 'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID',
       'DEST_CITY_MARKET_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR',
       'DEST_STATE_FIPS', 'DEST_STATE_NM', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'ARR_DELAY_NEW', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'FLIGHTS',
       'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY',
       'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY'],
      dtype='object')

#### **8. Find NaN or Null value**

In [ ]:
df.isna().sum()

YEAR                           0
MONTH                          0
DAY_OF_MONTH                   0
OP_UNIQUE_CARRIER              0
OP_CARRIER_AIRLINE_ID          0
OP_CARRIER                     0
TAIL_NUM                    5809
OP_CARRIER_FL_NUM              1
ORIGIN_AIRPORT_ID              0
ORIGIN_AIRPORT_SEQ_ID          0
ORIGIN_CITY_MARKET_ID          0
ORIGIN                         0
ORIGIN_CITY_NAME               0
ORIGIN_STATE_ABR               0
ORIGIN_STATE_FIPS              0
ORIGIN_STATE_NM                0
DEST_AIRPORT_ID                0
DEST_AIRPORT_SEQ_ID            0
DEST_CITY_MARKET_ID            0
DEST                           0
DEST_CITY_NAME                 0
DEST_STATE_ABR                 0
DEST_STATE_FIPS                0
DEST_STATE_NM                  0
CRS_DEP_TIME                   0
DEP_TIME                   29883
DEP_DELAY                  29940
DEP_DELAY_NEW              29940
CRS_ARR_TIME                   0
ARR_TIME                   31355
ARR_DELAY                  35397
ARR_DELAY_NEW              35397
CANCELLED                      0
CANCELLATION_CODE        1222552
DIVERTED                       0
CRS_ELAPSED_TIME               0
ACTUAL_ELAPSED_TIME        35397
AIR_TIME                   35397
FLIGHTS                        0
DISTANCE                       0
CARRIER_DELAY             929963
WEATHER_DELAY             929963
NAS_DELAY                 929963
SECURITY_DELAY            929963
LATE_AIRCRAFT_DELAY       929963
dtype: int64

#### **9. Cleaning NaN value**

In [ ]:
# Remove rows where TAIL NUM is NaN
df.dropna(subset=['TAIL_NUM'], inplace=True)

# Remove rows where OP_CARRIER_FL_NUM is NaN
df.dropna(subset=['OP_CARRIER_FL_NUM'], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1247828 entries, 0 to 1253637
Data columns (total 45 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   YEAR                   1247828 non-null  int64
 1   MONTH                  1247828 non-null  int64
 2   DAY_OF_MONTH           1247828 non-null  int64
 3   OP_UNIQUE_CARRIER      1247828 non-null  object
 4   OP_CARRIER_AIRLINE_ID  1247828 non-null  int64
 5   OP_CARRIER             1247828 non-null  object
 6   TAIL_NUM               1247828 non-null  object
 7   OP_CARRIER_FL_NUM      1247828 non-null  float64
 8   ORIGIN_AIRPORT_ID      1247828 non-null  int64
 9   ORIGIN_AIRPORT_SEQ_ID  1247828 non-null  int64
 10  ORIGIN_CITY_MARKET_ID  1247828 non-null  int64
 11  ORIGIN                 1247828 non-null  object
 12  ORIGIN_CITY_NAME       1247828 non-null  object
 13  ORIGIN_STATE_ABR       1247828 non-null  object
 14  ORIGIN_STATE_FIPS      1247828 non-null  int64
 15  ORIGIN_STATE_NM        1247828 non-null  object
 16  DEST_AIRPORT_ID        1247828 non-null  int64
 17  DEST_AIRPORT_SEQ_ID    1247828 non-null  int64
 18  DEST_CITY_MARKET_ID    1247828 non-null  int64
 19  DEST                   1247828 non-null  object
 20  DEST_CITY_NAME         1247828 non-null  object
 21  DEST_STATE_ABR         1247828 non-null  object
 22  DEST_STATE_FIPS        1247828 non-null  int64
 23  DEST_STATE_NM          1247828 non-null  object
 24  CRS_DEP_TIME           1247828 non-null  int64
 25  DEP_TIME               1223754 non-null  float64
 26  DEP_DELAY              1223697 non-null  float64
 27  DEP_DELAY_NEW          1223697 non-null  float64
 28  CRS_ARR_TIME           1247828 non-null  int64
 29  ARR_TIME               1222282 non-null  float64
 30  ARR_DELAY              1218240 non-null  float64
 31  ARR_DELAY_NEW          1218240 non-null  float64
 32  CANCELLED              1247828 non-null  float64
 33  CANCELLATION_CODE      25277 non-null    object
 34  DIVERTED               1247828 non-null  float64
 35  CRS_ELAPSED_TIME       1247828 non-null  float64
 36  ACTUAL_ELAPSED_TIME    1218240 non-null  float64
 37  AIR_TIME               1218240 non-null  float64
 38  FLIGHTS                1247828 non-null  float64
 39  DISTANCE               1247828 non-null  float64
 40  CARRIER_DELAY          323675 non-null   float64
 41  WEATHER_DELAY          323675 non-null   float64
 42  NAS_DELAY              323675 non-null   float64
 43  SECURITY_DELAY         323675 non-null   float64
 44  LATE_AIRCRAFT_DELAY    323675 non-null   float64
dtypes: float64(19), int64(14), object(12)
memory usage: 437.9+ MB

In [ ]:
df.isna().sum()

YEAR                           0
MONTH                          0
DAY_OF_MONTH                   0
OP_UNIQUE_CARRIER              0
OP_CARRIER_AIRLINE_ID          0
OP_CARRIER                     0
TAIL_NUM                       0
OP_CARRIER_FL_NUM              0
ORIGIN_AIRPORT_ID              0
ORIGIN_AIRPORT_SEQ_ID          0
ORIGIN_CITY_MARKET_ID          0
ORIGIN                         0
ORIGIN_CITY_NAME               0
ORIGIN_STATE_ABR               0
ORIGIN_STATE_FIPS              0
ORIGIN_STATE_NM                0
DEST_AIRPORT_ID                0
DEST_AIRPORT_SEQ_ID            0
DEST_CITY_MARKET_ID            0
DEST                           0
DEST_CITY_NAME                 0
DEST_STATE_ABR                 0
DEST_STATE_FIPS                0
DEST_STATE_NM                  0
CRS_DEP_TIME                   0
DEP_TIME                   24074
DEP_DELAY                  24131
DEP_DELAY_NEW              24131
CRS_ARR_TIME                   0
ARR_TIME                   25546
ARR_DELAY                  29588
ARR_DELAY_NEW              29588
CANCELLED                      0
CANCELLATION_CODE        1222551
DIVERTED                       0
CRS_ELAPSED_TIME               0
ACTUAL_ELAPSED_TIME        29588
AIR_TIME                   29588
FLIGHTS                        0
DISTANCE                       0
CARRIER_DELAY             924153
WEATHER_DELAY             924153
NAS_DELAY                 924153
SECURITY_DELAY            924153
LATE_AIRCRAFT_DELAY       924153
dtype: int64

In [ ]:
df

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1812,1808.0,-4.0,0.0,2015,1950.0,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,825,819.0,-6.0,0.0,923,916.0,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,1200,1157.0,-3.0,0.0,1457,1445.0,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,1621,1624.0,3.0,3.0,1732,1733.0,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,2110,2110.0,0.0,0.0,2242,2221.0,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1450,1446.0,-4.0,0.0,1608,1642.0,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,1250,1240.0,-10.0,0.0,1409,1343.0,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,1000,953.0,-7.0,0.0,1125,1122.0,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,944,940.0,-4.0,0.0,1158,1134.0,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,1250,1243.0,-7.0,0.0,1305,1254.0,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN

#### **10. Transform the year, day, and month into a single date in UTC+00 to standardize the dates**

In [ ]:
# Rename a column to DAY
df = df.rename(columns={'DAY_OF_MONTH': 'DAY'})

In [ ]:
# Get the timezone of the airport
def get_timezone(airport_code):
  airport_info = airports.get(airport_code)
  if airport_info:
    return airport_info['tz']
  # Handles case where IATA code is invalid
  return None

In [ ]:
# Add a column for the timezone of oriing
df['ORIGIN_TIMEZONE'] = df['ORIGIN'].apply(get_timezone)

In [ ]:
# # Try code with small numbers of rows
# df2 = df.iloc[0:100]

In [ ]:
# df2

In [ ]:
# The hours are in 'hhmm.0' format.
# They are transformed into 'hh:mm' format.
def convert_to_time(hhmm):
  # The code handles cases where flight times are missing (cancelled flights).
  if pd.isna(hhmm):
    return np.nan
  else:
    hhmm = int(hhmm)
    hours = hhmm // 100
    minutes = hhmm % 100
    return f"{hours:02}:{minutes:02}"

In [ ]:
df['CRS_DEP_TIME'] = df['CRS_DEP_TIME'].apply(convert_to_time)
df['DEP_TIME'] = df['DEP_TIME'].apply(convert_to_time)
df['CRS_ARR_TIME'] = df['CRS_ARR_TIME'].apply(convert_to_time)
df['ARR_TIME'] = df['ARR_TIME'].apply(convert_to_time)

In [ ]:
df

,YEAR,MONTH,DAY,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,ORIGIN_TIMEZONE
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,18:12,18:08,-4.0,0.0,20:15,19:50,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN,America/New_York
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,08:25,08:19,-6.0,0.0,09:23,09:16,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/New_York
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,12:00,11:57,-3.0,0.0,14:57,14:45,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/Chicago
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,16:21,16:24,3.0,3.0,17:32,17:33,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN,America/New_York
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,21:10,21:10,0.0,0.0,22:42,22:21,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,America/New_York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,14:50,14:46,-4.0,0.0,16:08,16:42,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0,America/New_York
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12:50,12:40,-10.0,0.0,14:09,13:43,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN,America/New_York
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10:00,09:53,-7.0,0.0,11:25,11:22,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN,America/New_York
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,09:44,09:40,-4.0,0.0,11:58,11:34,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN,America/New_York
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,12:50,12:43,-7.0,0.0,13:05,12:54,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN,America/New_York

In [ ]:
def convert_to_utc(row):
  # extract hour and minutes from 'hh:mm'
  try:
    hours, minutes = map(int, row['CRS_DEP_TIME'].split(':'))
  except AttributeError:
    return pd.NaT

  # Create datetime object
  dt = datetime(row['YEAR'], row['MONTH'], row['DAY'], hours, minutes, tzinfo=ZoneInfo(row['ORIGIN_TIMEZONE']))

  # Convert datetime into UTC time
  utc_dt = dt.astimezone(ZoneInfo('UTC'))

  return utc_dt

In [ ]:
# Add programmed UTC+00 datetime for departing airport
df['PROGRAMMED_DEP_TIME_UTC'] = df.apply(convert_to_utc, axis=1)

In [ ]:
df

,YEAR,MONTH,DAY,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,ORIGIN_TIMEZONE,PROGRAMMED_DEP_TIME_UTC
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,18:12,18:08,-4.0,0.0,20:15,19:50,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 22:12:00+00:00
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,08:25,08:19,-6.0,0.0,09:23,09:16,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 12:25:00+00:00
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,12:00,11:57,-3.0,0.0,14:57,14:45,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/Chicago,2024-07-01 17:00:00+00:00
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,16:21,16:24,3.0,3.0,17:32,17:33,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 20:21:00+00:00
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,21:10,21:10,0.0,0.0,22:42,22:21,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-02 01:10:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,14:50,14:46,-4.0,0.0,16:08,16:42,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0,America/New_York,2024-08-31 18:50:00+00:00
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12:50,12:40,-10.0,0.0,14:09,13:43,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10:00,09:53,-7.0,0.0,11:25,11:22,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 14:00:00+00:00
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,09:44,09:40,-4.0,0.0,11:58,11:34,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 13:44:00+00:00
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,12:50,12:43,-7.0,0.0,13:05,12:54,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00

In [ ]:
# Add actual departing time
def calculate_actual_dep_time(row):
  if pd.isna(row['DEP_DELAY']):
    return pd.NaT
  else:
    return row['PROGRAMMED_DEP_TIME_UTC'] + pd.to_timedelta(row['DEP_DELAY'], unit='m')

In [ ]:
df['ACTUAL_DEP_TIME_UTC'] = df.apply(calculate_actual_dep_time, axis=1)

In [ ]:
def calculate_programmed_arr_time(row):
  if pd.isna(row['CRS_ELAPSED_TIME']):
    return pd.NaT
  else:
    return row['PROGRAMMED_DEP_TIME_UTC'] + pd.to_timedelta(row['CRS_ELAPSED_TIME'], unit='m')

In [ ]:
df['PROGRAMMED_ARR_TIME_UTC'] = df.apply(calculate_programmed_arr_time, axis=1)

In [ ]:
df

,YEAR,MONTH,DAY,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,ORIGIN_TIMEZONE,PROGRAMMED_DEP_TIME_UTC,ACTUAL_DEP_TIME_UTC,PROGRAMMED_ARR_TIME_UTC
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,18:12,18:08,-4.0,0.0,20:15,19:50,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 22:12:00+00:00,2024-07-01 22:08:00+00:00,2024-07-02 00:15:00+00:00
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,08:25,08:19,-6.0,0.0,09:23,09:16,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 12:25:00+00:00,2024-07-01 12:19:00+00:00,2024-07-01 14:23:00+00:00
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,12:00,11:57,-3.0,0.0,14:57,14:45,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/Chicago,2024-07-01 17:00:00+00:00,2024-07-01 16:57:00+00:00,2024-07-01 18:57:00+00:00
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,16:21,16:24,3.0,3.0,17:32,17:33,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 20:21:00+00:00,2024-07-01 20:24:00+00:00,2024-07-01 21:32:00+00:00
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,21:10,21:10,0.0,0.0,22:42,22:21,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-02 01:10:00+00:00,2024-07-02 01:10:00+00:00,2024-07-02 02:42:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,14:50,14:46,-4.0,0.0,16:08,16:42,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0,America/New_York,2024-08-31 18:50:00+00:00,2024-08-31 18:46:00+00:00,2024-08-31 20:08:00+00:00
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12:50,12:40,-10.0,0.0,14:09,13:43,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00,2024-08-31 16:40:00+00:00,2024-08-31 18:09:00+00:00
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10:00,09:53,-7.0,0.0,11:25,11:22,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 14:00:00+00:00,2024-08-31 13:53:00+00:00,2024-08-31 15:25:00+00:00
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,09:44,09:40,-4.0,0.0,11:58,11:34,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 13:44:00+00:00,2024-08-31 13:40:00+00:00,2024-08-31 15:58:00+00:00
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,12:50,12:43,-7.0,0.0,13:05,12:54,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00,2024-08-31 16:43:00+00:00,2024-08-31 18:05:00+00:00

In [ ]:
def calculate_actual_arr_time(row):
  if pd.isna(row['ACTUAL_ELAPSED_TIME']):
    return pd.NaT
  else:
    return row['ACTUAL_DEP_TIME_UTC'] + pd.to_timedelta(row['ACTUAL_ELAPSED_TIME'], unit='m')

In [ ]:
df['ACTUAL_ARR_TIME_UTC'] = df.apply(calculate_actual_arr_time, axis=1)

In [ ]:
df

,YEAR,MONTH,DAY,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,ORIGIN_TIMEZONE,PROGRAMMED_DEP_TIME_UTC,ACTUAL_DEP_TIME_UTC,PROGRAMMED_ARR_TIME_UTC,ACTUAL_ARR_TIME_UTC
0,2024,7,1,9E,20363,9E,N131EV,4838.0,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,18:12,18:08,-4.0,0.0,20:15,19:50,-25.0,0.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 22:12:00+00:00,2024-07-01 22:08:00+00:00,2024-07-02 00:15:00+00:00,2024-07-01 23:50:00+00:00
1,2024,7,1,9E,20363,9E,N131EV,5011.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,08:25,08:19,-6.0,0.0,09:23,09:16,-7.0,0.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 12:25:00+00:00,2024-07-01 12:19:00+00:00,2024-07-01 14:23:00+00:00,2024-07-01 14:16:00+00:00
2,2024,7,1,9E,20363,9E,N131EV,5011.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47,Tennessee,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,12:00,11:57,-3.0,0.0,14:57,14:45,-12.0,0.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,America/Chicago,2024-07-01 17:00:00+00:00,2024-07-01 16:57:00+00:00,2024-07-01 18:57:00+00:00,2024-07-01 18:45:00+00:00
3,2024,7,1,9E,20363,9E,N131EV,5034.0,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,14122,1412202,30198,PIT,"Pittsburgh, PA",PA,42,Pennsylvania,16:21,16:24,3.0,3.0,17:32,17:33,1.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-01 20:21:00+00:00,2024-07-01 20:24:00+00:00,2024-07-01 21:32:00+00:00,2024-07-01 21:33:00+00:00
4,2024,7,1,9E,20363,9E,N131EV,5423.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,21:10,21:10,0.0,0.0,22:42,22:21,-21.0,0.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-07-02 01:10:00+00:00,2024-07-02 01:10:00+00:00,2024-07-02 02:42:00+00:00,2024-07-02 02:21:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,2024,8,31,YX,20452,YX,N882RW,5836.0,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,14:50,14:46,-4.0,0.0,16:08,16:42,34.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0,America/New_York,2024-08-31 18:50:00+00:00,2024-08-31 18:46:00+00:00,2024-08-31 20:08:00+00:00,2024-08-31 20:42:00+00:00
1253634,2024,8,31,YX,20452,YX,N882RW,5836.0,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10154,1015406,30154,ACK,"Nantucket, MA",MA,25,Massachusetts,12:50,12:40,-10.0,0.0,14:09,13:43,-26.0,0.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00,2024-08-31 16:40:00+00:00,2024-08-31 18:09:00+00:00,2024-08-31 17:43:00+00:00
1253635,2024,8,31,YX,20452,YX,N882RW,5848.0,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,12478,1247805,31703,JFK,"New York, NY",NY,36,New York,10:00,09:53,-7.0,0.0,11:25,11:22,-3.0,0.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 14:00:00+00:00,2024-08-31 13:53:00+00:00,2024-08-31 15:25:00+00:00,2024-08-31 15:22:00+00:00
1253636,2024,8,31,YX,20452,YX,N979RP,3482.0,11618,1161802,31703,EWR,"Newark, NJ",NJ,34,New Jersey,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,09:44,09:40,-4.0,0.0,11:58,11:34,-24.0,0.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 13:44:00+00:00,2024-08-31 13:40:00+00:00,2024-08-31 15:58:00+00:00,2024-08-31 15:34:00+00:00
1253637,2024,8,31,YX,20452,YX,N979RP,3655.0,11986,1198603,31986,GRR,"Grand Rapids, MI",MI,26,Michigan,13930,1393008,30977,ORD,"Chicago, IL",IL,17,Illinois,12:50,12:43,-7.0,0.0,13:05,12:54,-11.0,0.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN,America/New_York,2024-08-31 16:50:00+00:00,2024-08-31 16:43:00+00:00,2024-08-31 18:05:00+00:00,2024-08-31 17:54:00+00:00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1247828 entries, 0 to 1253637
Data columns (total 50 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   YEAR                     1247828 non-null  int64
 1   MONTH                    1247828 non-null  int64
 2   DAY                      1247828 non-null  int64
 3   OP_UNIQUE_CARRIER        1247828 non-null  object
 4   OP_CARRIER_AIRLINE_ID    1247828 non-null  int64
 5   OP_CARRIER               1247828 non-null  object
 6   TAIL_NUM                 1247828 non-null  object
 7   OP_CARRIER_FL_NUM        1247828 non-null  float64
 8   ORIGIN_AIRPORT_ID        1247828 non-null  int64
 9   ORIGIN_AIRPORT_SEQ_ID    1247828 non-null  int64
 10  ORIGIN_CITY_MARKET_ID    1247828 non-null  int64
 11  ORIGIN                   1247828 non-null  object
 12  ORIGIN_CITY_NAME         1247828 non-null  object
 13  ORIGIN_STATE_ABR         1247828 non-null  object
 14  ORIGIN_STATE_FIPS        1247828 non-null  int64
 15  ORIGIN_STATE_NM          1247828 non-null  object
 16  DEST_AIRPORT_ID          1247828 non-null  int64
 17  DEST_AIRPORT_SEQ_ID      1247828 non-null  int64
 18  DEST_CITY_MARKET_ID      1247828 non-null  int64
 19  DEST                     1247828 non-null  object
 20  DEST_CITY_NAME           1247828 non-null  object
 21  DEST_STATE_ABR           1247828 non-null  object
 22  DEST_STATE_FIPS          1247828 non-null  int64
 23  DEST_STATE_NM            1247828 non-null  object
 24  CRS_DEP_TIME             1247828 non-null  object
 25  DEP_TIME                 1223754 non-null  object
 26  DEP_DELAY                1223697 non-null  float64
 27  DEP_DELAY_NEW            1223697 non-null  float64
 28  CRS_ARR_TIME             1247828 non-null  object
 29  ARR_TIME                 1222282 non-null  object
 30  ARR_DELAY                1218240 non-null  float64
 31  ARR_DELAY_NEW            1218240 non-null  float64
 32  CANCELLED                1247828 non-null  float64
 33  CANCELLATION_CODE        25277 non-null    object
 34  DIVERTED                 1247828 non-null  float64
 35  CRS_ELAPSED_TIME         1247828 non-null  float64
 36  ACTUAL_ELAPSED_TIME      1218240 non-null  float64
 37  AIR_TIME                 1218240 non-null  float64
 38  FLIGHTS                  1247828 non-null  float64
 39  DISTANCE                 1247828 non-null  float64
 40  CARRIER_DELAY            323675 non-null   float64
 41  WEATHER_DELAY            323675 non-null   float64
 42  NAS_DELAY                323675 non-null   float64
 43  SECURITY_DELAY           323675 non-null   float64
 44  LATE_AIRCRAFT_DELAY      323675 non-null   float64
 45  ORIGIN_TIMEZONE          1247828 non-null  object
 46  PROGRAMMED_DEP_TIME_UTC  1247828 non-null  datetime64[ns, UTC]
 47  ACTUAL_DEP_TIME_UTC      1223697 non-null  datetime64[ns, UTC]
 48  PROGRAMMED_ARR_TIME_UTC  1247828 non-null  datetime64[ns, UTC]
 49  ACTUAL_ARR_TIME_UTC      1218240 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(17), int64(12), object(17)
memory usage: 485.5+ MB

In [ ]:
# df2 = df.iloc[:10]

In [ ]:
# Removing duplicate information
df = df.drop(columns=[ "YEAR", "MONTH", "DAY",
                       "OP_CARRIER",
                       "ORIGIN_AIRPORT_SEQ_ID", "ORIGIN_CITY_MARKET_ID", "ORIGIN_CITY_NAME", "ORIGIN_STATE_FIPS",
                       "DEST_AIRPORT_SEQ_ID", "DEST_CITY_MARKET_ID", "DEST_CITY_NAME", "DEST_STATE_FIPS",
                        "CRS_DEP_TIME", "DEP_TIME", "DEP_DELAY_NEW",
                        "CRS_ARR_TIME", "ARR_TIME", "ARR_DELAY_NEW",
                        "ORIGIN_TIMEZONE"])

In [ ]:
df

,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST,DEST_STATE_ABR,DEST_STATE_NM,DEP_DELAY,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,PROGRAMMED_DEP_TIME_UTC,ACTUAL_DEP_TIME_UTC,PROGRAMMED_ARR_TIME_UTC,ACTUAL_ARR_TIME_UTC
0,9E,20363,N131EV,4838.0,14122,PIT,PA,Pennsylvania,12478,JFK,NY,New York,-4.0,-25.0,0.0,NaN,0.0,123.0,102.0,70.0,1.0,340.0,NaN,NaN,NaN,NaN,NaN,2024-07-01 22:12:00+00:00,2024-07-01 22:08:00+00:00,2024-07-02 00:15:00+00:00,2024-07-01 23:50:00+00:00
1,9E,20363,N131EV,5011.0,11433,DTW,MI,Michigan,13244,MEM,TN,Tennessee,-6.0,-7.0,0.0,NaN,0.0,118.0,117.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,2024-07-01 12:25:00+00:00,2024-07-01 12:19:00+00:00,2024-07-01 14:23:00+00:00,2024-07-01 14:16:00+00:00
2,9E,20363,N131EV,5011.0,13244,MEM,TN,Tennessee,11433,DTW,MI,Michigan,-3.0,-12.0,0.0,NaN,0.0,117.0,108.0,85.0,1.0,610.0,NaN,NaN,NaN,NaN,NaN,2024-07-01 17:00:00+00:00,2024-07-01 16:57:00+00:00,2024-07-01 18:57:00+00:00,2024-07-01 18:45:00+00:00
3,9E,20363,N131EV,5034.0,11433,DTW,MI,Michigan,14122,PIT,PA,Pennsylvania,3.0,1.0,0.0,NaN,0.0,71.0,69.0,39.0,1.0,201.0,NaN,NaN,NaN,NaN,NaN,2024-07-01 20:21:00+00:00,2024-07-01 20:24:00+00:00,2024-07-01 21:32:00+00:00,2024-07-01 21:33:00+00:00
4,9E,20363,N131EV,5423.0,12478,JFK,NY,New York,10821,BWI,MD,Maryland,0.0,-21.0,0.0,NaN,0.0,92.0,71.0,45.0,1.0,184.0,NaN,NaN,NaN,NaN,NaN,2024-07-02 01:10:00+00:00,2024-07-02 01:10:00+00:00,2024-07-02 02:42:00+00:00,2024-07-02 02:21:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253633,YX,20452,N882RW,5836.0,10154,ACK,MA,Massachusetts,12478,JFK,NY,New York,-4.0,34.0,0.0,NaN,0.0,78.0,116.0,41.0,1.0,199.0,0.0,0.0,34.0,0.0,0.0,2024-08-31 18:50:00+00:00,2024-08-31 18:46:00+00:00,2024-08-31 20:08:00+00:00,2024-08-31 20:42:00+00:00
1253634,YX,20452,N882RW,5836.0,12478,JFK,NY,New York,10154,ACK,MA,Massachusetts,-10.0,-26.0,0.0,NaN,0.0,79.0,63.0,36.0,1.0,199.0,NaN,NaN,NaN,NaN,NaN,2024-08-31 16:50:00+00:00,2024-08-31 16:40:00+00:00,2024-08-31 18:09:00+00:00,2024-08-31 17:43:00+00:00
1253635,YX,20452,N882RW,5848.0,14524,RIC,VA,Virginia,12478,JFK,NY,New York,-7.0,-3.0,0.0,NaN,0.0,85.0,89.0,57.0,1.0,288.0,NaN,NaN,NaN,NaN,NaN,2024-08-31 14:00:00+00:00,2024-08-31 13:53:00+00:00,2024-08-31 15:25:00+00:00,2024-08-31 15:22:00+00:00
1253636,YX,20452,N979RP,3482.0,11618,EWR,NJ,New Jersey,11986,GRR,MI,Michigan,-4.0,-24.0,0.0,NaN,0.0,134.0,114.0,87.0,1.0,605.0,NaN,NaN,NaN,NaN,NaN,2024-08-31 13:44:00+00:00,2024-08-31 13:40:00+00:00,2024-08-31 15:58:00+00:00,2024-08-31 15:34:00+00:00
1253637,YX,20452,N979RP,3655.0,11986,GRR,MI,Michigan,13930,ORD,IL,Illinois,-7.0,-11.0,0.0,NaN,0.0,75.0,71.0,32.0,1.0,137.0,NaN,NaN,NaN,NaN,NaN,2024-08-31 16:50:00+00:00,2024-08-31 16:43:00+00:00,2024-08-31 18:05:00+00:00,2024-08-31 17:54:00+00:00

In [ ]:
df = df.rename(columns={'OP_UNIQUE_CARRIER': 'CODE_CARRIER',
                        'OP_CARRIER_AIRLINE_ID': 'ID_CARRIER',
                        'OP_CARRIER_FL_NUM': 'FLIGHT_NUMBER',
                        'ORIGIN': 'ORIGIN_IATA',
                        'DEST': 'DEST_IATA',
                        'CRS_ELAPSED_TIME': 'PROGRAMMED_TOTAL_FLIGHT_TIME',
                        'ACTUAL_ELAPSED_TIME': 'ACTUAL_TOTAL_FLIGHT_TIME',
                        'PROGRAMMED_DEP_TIME_UTC': 'PROGRAMMED_DEPARTING_TIME_UTC',
                        'ACTUAL_DEP_TIME_UTC': 'ACTUAL_DEPARTING_TIME_UTC',
                        'PROGRAMMED_ARR_TIME_UTC': 'PROGRAMMED_ARRIVING_TIME_UTC',
                        'ACTUAL_ARR_TIME_UTC': 'ACTUAL_ARRIVING_TIME_UTC'})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1247828 entries, 0 to 1253637
Data columns (total 31 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   ID_CARRIER                     1247828 non-null  object
 1   ID_AIRLINE                     1247828 non-null  int64
 2   TAIL_NUM                       1247828 non-null  object
 3   FLIGHT_NUMBER                  1247828 non-null  float64
 4   ORIGIN_AIRPORT_ID              1247828 non-null  int64
 5   ORIGIN_IATA                    1247828 non-null  object
 6   ORIGIN_STATE_ABR               1247828 non-null  object
 7   ORIGIN_STATE_NM                1247828 non-null  object
 8   DEST_AIRPORT_ID                1247828 non-null  int64
 9   DEST_IATA                      1247828 non-null  object
 10  DEST_STATE_ABR                 1247828 non-null  object
 11  DEST_STATE_NM                  1247828 non-null  object
 12  DEP_DELAY                      1223697 non-null  float64
 13  ARR_DELAY                      1218240 non-null  float64
 14  CANCELLED                      1247828 non-null  float64
 15  CANCELLATION_CODE              25277 non-null    object
 16  DIVERTED                       1247828 non-null  float64
 17  PROGRAMMED_TOTAL_FLIGHT_TIME   1247828 non-null  float64
 18  ACTUAL_TOTAL_FLIGHT_TIME       1218240 non-null  float64
 19  AIR_TIME                       1218240 non-null  float64
 20  FLIGHTS                        1247828 non-null  float64
 21  DISTANCE                       1247828 non-null  float64
 22  CARRIER_DELAY                  323675 non-null   float64
 23  WEATHER_DELAY                  323675 non-null   float64
 24  NAS_DELAY                      323675 non-null   float64
 25  SECURITY_DELAY                 323675 non-null   float64
 26  LATE_AIRCRAFT_DELAY            323675 non-null   float64
 27  PROGRAMMED_DEPARTING_TIME_UTC  1247828 non-null  datetime64[ns, UTC]
 28  ACTUAL_DEPARTING_TIME_UTC      1223697 non-null  datetime64[ns, UTC]
 29  PROGRAMMED_ARRIVING_TIME_UTC   1247828 non-null  datetime64[ns, UTC]
 30  ACTUAL_ARRIVING_TIME_UTC       1218240 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(15), int64(3), object(9)
memory usage: 304.6+ MB

In [ ]:
df.isna().sum()

ID_CARRIER                             0
ID_AIRLINE                             0
TAIL_NUM                               0
FLIGHT_NUMBER                          0
ORIGIN_AIRPORT_ID                      0
ORIGIN_IATA                            0
ORIGIN_STATE_ABR                       0
ORIGIN_STATE_NM                        0
DEST_AIRPORT_ID                        0
DEST_IATA                              0
DEST_STATE_ABR                         0
DEST_STATE_NM                          0
DEP_DELAY                          24131
ARR_DELAY                          29588
CANCELLED                              0
CANCELLATION_CODE                1222551
DIVERTED                               0
PROGRAMMED_TOTAL_FLIGHT_TIME           0
ACTUAL_TOTAL_FLIGHT_TIME           29588
AIR_TIME                           29588
FLIGHTS                                0
DISTANCE                               0
CARRIER_DELAY                     924153
WEATHER_DELAY                     924153
NAS_DELAY                         924153
SECURITY_DELAY                    924153
LATE_AIRCRAFT_DELAY               924153
PROGRAMMED_DEPARTING_TIME_UTC          0
ACTUAL_DEPARTING_TIME_UTC          24131
PROGRAMMED_ARRIVING_TIME_UTC           0
ACTUAL_ARRIVING_TIME_UTC           29588
dtype: int64

In [ ]:
# Saving cleaned data
df.to_csv("/content/drive/MyDrive/cleaned csv/Airport cleaned data.csv", index=False)